services:
  frontend:
    container_name: wamp-client
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  backend:
    container_name: wamp-server
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
